server:
  port: 8181
  error:
    include-message: always
logging:
  level:
    com:
      example:
        shiftservice: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  circuitbreaker:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
spring:
  application:
    name: shift-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shift}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  cache:
    cache-names: shifts,workSchedules
    caffeine:
      spec:
        - maximumSize=500
        - expireAfterAccess=3600s
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASE_URL:http://localhost:9411/}

