server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    register-with-eureka: false
  instance:
    prefer-ip-address: true
resilience4j:
  circuitbreaker:
    instances:
      addressServiceFallback:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        registerHealthIndicator: true
      employeeServiceFallback:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        registerHealthIndicator: true
      shiftServiceFallback:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        registerHealthIndicator: true
      emailServiceFallback:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        registerHealthIndicator: true
    timelimiter:
      instances:
        addressServiceFallback:
          timeoutDuration: 2s
        employeeServiceFallback:
          timeoutDuration: 2s
        shiftServiceFallback:
          timeoutDuration: 2s
        emailServiceFallback:
          timeoutDuration: 10s
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: address-service
          uri: lb://address-service
          predicates:
            - Path=/api/v1/address/**
          filters:
            - name: CircuitBreaker
              args:
                name: addressServiceFallback
                fallbackUri: forward:/fallback/address
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/v1/employee/**
          filters:
            - name: CircuitBreaker
              args:
                name: employeeServiceFallback
                fallbackUri: forward:/fallback/employee
        - id: shift-service
          uri: lb://shift-service
          predicates:
            - Path=/api/v1/shift/**
          filters:
            - name: CircuitBreaker
              args:
                name: shiftServiceFallback
                fallbackUri: forward:/fallback/shift
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/api/v1/email/**
          filters:
            - name: CircuitBreaker
              args:
                name: emailServiceFallback
                fallbackUri: forward:/fallback/email
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASE_URL:http://localhost:9411/}