server:
  port: 8383
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    com:
      example:
        emailservice: debug
feign:
  circuitbreaker:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
company:
  name: TotallyRealCompany
  contact-information: 111-111-1111
spring:
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



